paths:
  /user/login:
    post:
      tags:
        - User
      summary: 로그인 로직 처리 및 토큰 발급 (JWT Token)
      parameters:
        - name: userIDPW
          in: body
          required: true
          schema:
            properties:
              id:
                type: string
                example: "umcweb"
              pw:
                type: string
                example: "1234"
      responses:
        '200':
          description: 로그인 성공
        '400':
          description: 입력 값 없음
        '404':
          description: 로그인 실패 (아이디, 비밀번호 불일치)

  /user/payload:
      get:
        tags:
          - User
        summary: JWT Token 검증
        parameters:
          - name: Authorization
            in: header
            type: string
            description: auth JWT Token
                
      responses:
        '200':
          description: 토큰 검증 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                    "id": "umcweb",
                    "name": "UMC 웹 파이팅"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '401':
          description: 유효하지 않은 토큰입니다.
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: SIGNIN4005
              message:
                type: string
                example: 유효하지 않은 토큰입니다.

        '419':
          description: 토큰이 만료되었습니다.
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 419
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: SIGNIN4004
              message:
                type: string
                example: 토큰이 만료되었습니다. JWT Expired.

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
